### PR TITLE
:construction_worker: NEP29: Run CI and Docs build on Python 3.11

### PR DESCRIPTION
**Pull request by weiji14**
Run Continuous Integration tests, workflows and documentation build on Python 3.11. Need to bump spatialpandas, datashader, pyarrow, llvmlite and numba to get Python 3.11 compatible wheels.

Bumps [python](https://github.com/python/cpython) from 3.10.11 to 3.11.3.
  - [Release notes](https://github.com/python/cpython/releases/tag/v3.11.3)
  - [Changelog](https://docs.python.org/3/whatsnew/3.11.html)
  - [Commits](https://github.com/python/cpython/compare/v3.10.11...v3.11.3)

Notes:
- Now running tests on the `spatial` extras, that was omitted in #89 due to incompatibilities on the `datashader`/`spatialpandas` stack.

Supersedes #89 and #29.

### CODE REVIEW

**Comment by weiji14** [comment]
Unit tests and docs build failing with `AttributeError: module 'inspect' has no attribute 'getargspec'` with `datashader`. Traceback from https://github.com/weiji14/zen3geo/actions/runs/5096252611/jobs/9161946910?pr=103#step:5:119:

```python-traceback
___ [doctest] zen3geo.datapipes.datashader.DatashaderRasterizerIterDataPipe ____
127     >>> dp_canvas = IterableWrapper(iterable=[canvas])
128     ...
129     >>> # Rasterize vector point geometries onto blank canvas
130     >>> dp_datashader = dp_canvas.rasterize_with_datashader(
131     ...     vector_datapipe=dp_vector
132     ... )
133     ...
134     >>> # Loop or iterate over the DataPipe stream
135     >>> it = iter(dp_datashader)
136     >>> dataarray = next(it)
UNEXPECTED EXCEPTION: AttributeError("module 'inspect' has no attribute 'getargspec'\nThis exception is thrown by __iter__ of DatashaderRasterizerIterDataPipe(agg=None, kwargs={}, source_datapipe=IterableWrapperIterDataPipe, vector_datapipe=IterableWrapperIterDataPipe)")
Traceback (most recent call last):
  File "/home/runner/.cache/pypoetry/virtualenvs/zen3geo-wNxkC0DI-py3.11/lib/python3.11/site-packages/toolz/functoolz.py", line 457, in memof
    return cache[k]
           ~~~~~^^^
KeyError: (<datashader.glyphs.points.MultiPointGeometry object at 0x7f92287e3750>, CPUDispatcher(<function LinearAxis.mapper at 0x7f92c7144720>), CPUDispatcher(<function LinearAxis.mapper at 0x7f92c7144720>), <function make_info.<locals>.<lambda> at 0x7f922895b6a0>, CPUDispatcher(<function append at 0x7f922895b920>), False)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/runner/.cache/pypoetry/virtualenvs/zen3geo-wNxkC0DI-py3.11/lib/python3.11/site-packages/datashader/glyphs/glyph.py", line 151, in _expand_aggs_and_cols
    append_args = inspect.getargspec(append.py_func).args
                  ^^^^^^^^^^^^^^^^^^
AttributeError: module 'inspect' has no attribute 'getargspec'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.3/x64/lib/python3.11/doctest.py", line 1351, in __run
    exec(compile(example.source, filename, "single",
  File "<doctest zen3geo.datapipes.datashader.DatashaderRasterizerIterDataPipe[14]>", line 1, in <module>
  File "/home/runner/.cache/pypoetry/virtualenvs/zen3geo-wNxkC0DI-py3.11/lib/python3.11/site-packages/torch/utils/data/datapipes/_hook_iterator.py", line 173, in wrap_generator
    response = gen.send(None)
               ^^^^^^^^^^^^^^
  File "/home/runner/work/zen3geo/zen3geo/zen3geo/datapipes/datashader.py", line 229, in __iter__
    raster: xr.DataArray = canvas.points(
                           ^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/zen3geo-wNxkC0DI-py3.11/lib/python3.11/site-packages/datashader/core.py", line 219, in points
    return bypixel(source, self, glyph, agg)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/zen3geo-wNxkC0DI-py3.11/lib/python3.11/site-packages/datashader/core.py", line 1260, in bypixel
    return bypixel.pipeline(source, schema, canvas, glyph, agg, antialias=antialias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/zen3geo-wNxkC0DI-py3.11/lib/python3.11/site-packages/datashader/utils.py", line 112, in __call__
    return lk[cls](head, *rest, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/zen3geo-wNxkC0DI-py3.11/lib/python3.11/site-packages/datashader/data_libraries/pandas.py", line 17, in pandas_pipeline
    return glyph_dispatch(glyph, df, schema, canvas, summary, antialias=antialias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/zen3geo-wNxkC0DI-py3.11/lib/python3.11/site-packages/datashader/utils.py", line 112, in __call__
    return lk[cls](head, *rest, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/zen3geo-wNxkC0DI-py3.11/lib/python3.11/site-packages/datashader/data_libraries/pandas.py", line 31, in default
    extend = glyph._build_extend(x_mapper, y_mapper, info, append, antialias_stage_2)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/zen3geo-wNxkC0DI-py3.11/lib/python3.11/site-packages/toolz/functoolz.py", line 461, in memof
    cache[k] = result = func(*args, **kwargs)
                        ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/zen3geo-wNxkC0DI-py3.11/lib/python3.11/site-packages/datashader/glyphs/points.py", line 235, in _build_extend
    @self.expand_aggs_and_cols(append)
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/zen3geo-wNxkC0DI-py3.11/lib/python3.11/site-packages/datashader/glyphs/glyph.py", line 135, in expand_aggs_and_cols
    return self._expand_aggs_and_cols(append, self.ndims, self.antialiased)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/zen3geo-wNxkC0DI-py3.11/lib/python3.11/site-packages/datashader/glyphs/glyph.py", line 154, in _expand_aggs_and_cols
    append_args = inspect.getargspec(append).args
                  ^^^^^^^^^^^^^^^^^^
AttributeError: module 'inspect' has no attribute 'getargspec'
This exception is thrown by __iter__ of DatashaderRasterizerIterDataPipe(agg=None, kwargs={}, source_datapipe=IterableWrapperIterDataPipe, vector_datapipe=IterableWrapperIterDataPipe)
/home/runner/work/zen3geo/zen3geo/zen3geo/datapipes/datashader.py:136: UnexpectedException
```

Need to wait for `datashader>=0.14.5` which contains the https://github.com/holoviz/datashader/pull/1205/commits/b785748d616941caa0ca9c065d96cf7df2c1ec45 patch in https://github.com/holoviz/datashader/pull/1205 that changed the deprecated `inspect.getargspec` function to `inspect.getfullargspec`.
